defaultStake: 10000
defaultFee: 2000
borChainId: 15001
heimdallChainId: heimdall-15001
contractsBranch: anvil-pos
genesisContractsBranch: master
sprintSize:
  - '64'
blockNumber:
  - '0'
blockTime:
  - '2'
numOfBorValidators: 3
numOfBorSentries: 0
numOfBorArchiveNodes: 0
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
ethURL: http://anvil:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: 'https://github.com/maticnetwork/bor.git#develop'
heimdallDockerBuildContext: 'https://github.com/maticnetwork/heimdall.git#develop'
sprintSizeBlockNumber:
  - '0'
devnetBorFlags: config,config,config
mnemonic: 'clock radar mass judge dismiss just intact mind resemble fringe diary casino'
