# Repositories
borRepo: https://github.com/shibaone/bor.git
borBranch: v1.3.7-bone-candidate

heimdallRepo: https://github.com/shibaone/heimdall.git
heimdallBranch: v1.0.7-bone-candidate

contractsRepo: https://github.com/shibaone/contracts.git
contractsBranch: v1.0.0-bone/node-16

genesisContractsRepo: https://github.com/shibaone/genesis-contracts.git
genesisContractsBranch: master

# Defaults
devnetType: docker
defaultStake: 10000
defaultFee: 2000

# L1
ethURL: http://ganacheURL:9545 # use localhost for local deployments
ethHostUser: ubuntu

# Heimdall
heimdallChainId: heimdall-173
heimdallDockerBuildContext: https://github.com/shibaone/heimdall.git#v1.0.7-bone-candidate

# Bor
borChainId: 173
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '5'
numOfBorValidators: 3
numOfBorSentries: 2
numOfBorArchiveNodes: 1
borDockerBuildContext: https://github.com/shibaone/bor.git#v1.3.7-bone-candidate
devnetBorUsers: ubuntu,ubuntu
devnetBorHosts: ["ec2-xx-xxx-xx-xxx.eu-west-1.compute.amazonaws.com"] # use localhost for local deployments
devnetBorFlags: config,config

# Erigon
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
