# Repositories
borRepo: https://github.com/shibaone/bor.git
borBranch: v2.0.4-bone-candidate

heimdallRepo: https://github.com/shibaone/heimdall.git
heimdallBranch: v1.2.3-bone-candidate

contractsRepo: https://github.com/shibaone/pos-contracts.git
contractsBranch: anvil-pos

genesisContractsRepo: https://github.com/shibaone/genesis-contracts.git
genesisContractsBranch: master

# Defaults
devnetType: docker
defaultStake: 10000
defaultFee: 2000

# L1
ethURL: http://anvil:9545 # use localhost for local deployments
ethHostUser: ubuntu

# Misc
mnemonic: "clock radar mass judge dismiss just intact mind resemble fringe diary casino" 

# Heimdall
heimdallChainId: heimdall-15005
heimdallDockerBuildContext: https://github.com/shibaone/heimdall.git#develop

# Bor
borChainId: 15005
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '5'
numOfBorValidators: 2
numOfBorSentries: 1
numOfBorArchiveNodes: 0
borDockerBuildContext: https://github.com/shibaone/bor.git#develop
devnetBorUsers: ubuntu,ubuntu,ubuntu
devnetBorFlags: config,config,config

# Erigon
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
