defaultStake: 10000
defaultFee: 2000
borChainId: 173
heimdallChainId: heimdall-173
borRepo: https://github.com/shibaone/bor.git
borBranch: v1.3.7-bone-candidate
heimdallRepo: https://github.com/shibaone/heimdall.git
heimdallBranch: v1.0.7-bone-candidate
contractsRepo: https://github.com/shibaone/contracts.git
contractsBranch: v1.0.0-bone/node-16
genesisContractsRepo: https://github.com/shibaone/genesis-contracts.git
genesisContractsBranch: master
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '2'
numOfBorValidators: 3
numOfBorSentries: 2
numOfBorArchiveNodes: 1
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
ethURL: http://ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetHeimdallHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
devnetBorFlags:
  - config
  - config
borDockerBuildContext: https://github.com/shibaone/bor.git#v1.3.7-bone-candidate
heimdallDockerBuildContext: https://github.com/shibaone/heimdall.git#v1.0.7-bone-candidate
