defaultStake: 10000
defaultFee: 2000
borChainId: 15001
heimdallChainId: heimdall-15001
borRepo: https://github.com/shibaone/bor.git
borBranch: v1.1.0-bone-beta-3
heimdallRepo: https://github.com/shibaone/heimdall.git
heimdallBranch: v1.0.2-bone-beta-3
contractsRepo: https://github.com/maticnetwork/contracts.git
contractsBranch: mardizzone/node-16
genesisContractsRepo: https://github.com/maticnetwork/genesis-contracts.git
genesisContractsBranch: master
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '2'
numOfBorValidators: 1
numOfBorSentries: 1
numOfBorArchiveNodes: 0
numOfErigonValidators: 1
numOfErigonSentries: 1
numOfErigonArchiveNodes: 0
ethURL: https://eth-sepolia.g.alchemy.com/v2/fxvGAhZVTo8gG8frWX7TyikGQ_0eoBd2
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetHeimdallHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
devnetBorFlags:
  - config
  - config
borDockerBuildContext: https://github.com/shibaone/bor.git#v1.1.0-bone-beta-3
heimdallDockerBuildContext: https://github.com/shibaone/heimdall.git#develop
