defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-15005
borRepo: https://github.com/shibaone/bor.git
borBranch: develop
heimdallRepo: https://github.com/shibaone/heimdall.git
heimdallBranch: develop
contractsRepo: https://github.com/shibaone/pos-contracts.git
contractsBranch: anvil-pos
genesisContractsRepo: https://github.com/shibaone/genesis-contracts.git
genesisContractsBranch: master
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '5'
numOfBorValidators: 2
numOfBorSentries: 0
numOfBorArchiveNodes: 0
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
ethURL: http://ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetHeimdallHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
devnetBorFlags:
  - config
  - config
borDockerBuildContext: https://github.com/shibaone/bor.git#develop
heimdallDockerBuildContext: https://github.com/shibaone/heimdall.git#develop
